# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MediaPicker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MediaPicker
  pod 'ReactiveSwift', '~> 6.1'
  pod "Texture"

end
